#!/usr/bin/env python3
"""Generate src/util/uniwidth_table.h from a wcwidth dump.

mosh's diff protocol requires the client and the server to compute the same
width for the same character; if they disagree, everything after the first
divergent wide character is misplaced, silently. The Windows port cannot use
wcwidth() -- MSVC has none, and its wchar_t is 16 bits -- so it needs its own
table, and that table has to agree with the glibc the server is running.

So the table is derived from glibc's own answers rather than re-derived from
the Unicode database: matching the reference implementation is the requirement,
and re-deriving it would only introduce a second place to be wrong.

Produce the dump with scripts/dump-wcwidth.c on a glibc machine:

    cc -O2 -o dump scripts/dump-wcwidth.c && ./dump > widths.txt
    scripts/gen-uniwidth.py widths.txt > src/util/uniwidth_table.h

Each dump line is "START END WIDTH" in hex, hex, decimal, covering
U+0000..U+10FFFF with no gaps.
"""

import sys
import re


def main():
    if len(sys.argv) != 2:
        sys.stderr.write("usage: gen-uniwidth.py <widths.txt>\n")
        return 2

    ranges = []
    with open(sys.argv[1]) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            m = re.match(r"^([0-9A-Fa-f]+) ([0-9A-Fa-f]+) (-?\d+)$", line)
            if not m:
                sys.stderr.write("cannot parse: %s\n" % line)
                return 1
            ranges.append((int(m.group(1), 16), int(m.group(2), 16), int(m.group(3))))

    ranges.sort()

    # Sanity: contiguous, complete, and only the four widths mosh allows.
    expect = 0
    for start, end, width in ranges:
        if start != expect:
            sys.stderr.write("gap or overlap at U+%04X (expected U+%04X)\n" % (start, expect))
            return 1
        if width not in (-1, 0, 1, 2):
            sys.stderr.write("width %d at U+%04X is outside {-1,0,1,2}\n" % (width, start))
            return 1
        expect = end + 1
    if expect != 0x110000:
        sys.stderr.write("dump ends at U+%04X, expected U+110000\n" % expect)
        return 1

    # Merge adjacent ranges of equal width, then store only each range's start:
    # the ranges tile the space, so a lookup is "the last start <= cp".
    merged = []
    for start, end, width in ranges:
        if merged and merged[-1][1] == width:
            continue
        merged.append((start, width))

    out = sys.stdout
    out.write("/* Generated by scripts/gen-uniwidth.py -- do not edit.\n")
    out.write(" *\n")
    out.write(" * Character widths, derived from glibc's wcwidth(). See uniwidth.h for why\n")
    out.write(" * this is a snapshot of a reference implementation rather than a fresh\n")
    out.write(" * derivation from the Unicode database.\n")
    out.write(" */\n\n")
    out.write("#ifndef UNIWIDTH_TABLE_H\n#define UNIWIDTH_TABLE_H\n\n")
    out.write("#include <cstdint>\n\n")
    out.write("namespace Util {\n\n")
    out.write("/* Each entry starts a run that continues until the next entry's start.\n")
    out.write("   The runs tile U+0000..U+10FFFF, so a lookup is a binary search for the\n")
    out.write("   last start <= the code point. */\n")
    out.write("struct UniWidthRun\n{\n  uint32_t start;\n  int8_t width;\n};\n\n")
    out.write("static const UniWidthRun uniwidth_runs[] = {\n")
    for i in range(0, len(merged), 4):
        chunk = merged[i:i + 4]
        out.write("  " + " ".join("{ 0x%06X, %2d }," % (s, w) for s, w in chunk) + "\n")
    out.write("};\n\n")
    out.write("static const size_t uniwidth_runs_count = sizeof( uniwidth_runs ) / sizeof( *uniwidth_runs );\n\n")
    out.write("}\n\n#endif\n")

    sys.stderr.write("%d input ranges -> %d runs\n" % (len(ranges), len(merged)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
